#!/bin/bash
argument=$1

if [ $argument == "VPSX" ]; then
    rm /usr/bin/sv
    rm /usr/bin/vp
    rm /usr/bin/vs
    rm /usr/bin/vx
    rm /usr/bin/vpx
    rm /usr/bin/vsx
    

else 
    rm $argument

fi
