#!/bin/bash
# this script should only be used to create a skeleton python script

file=$1

make_file ()
{
    echo "#!/usr/bin/python2.7" > $file
    vim $file
    chmod 755 $file
}

if [ -a $file ]; then
    vim $file        

else
    make_file

fi
