#!/bin/bash

file=$1

make_file ()
{
    touch $file
    echo "#!/usr/bin/python2.7" > $file
    vim $file
    chmod 755 $file
    ./$file

}

if [ -a  $file ]; then
    vim $file
    ./$file

else
    make_file

fi


